import os


## DEFINING SOME COMMON CONSTANTS FOR TRAINING PIPELINE
TARGET_COLUMN = "case_status"
PIPELINE_NAME = "USVisa"
ARTIFACT_DIR = "artifacts"
FILE_NAME = "Visadataset.csv"
TRAIN_FILE_NAME = "train.csv"
TEST_FILE_NAME = "test.csv"

## DATA INGESTION RELATED CONSTANTS STARTS WITH DATA_INGESTION VAR NAME 
DATA_INGESTION_COLLECTION_NAME = "VisaData"
DATA_INGESTION_DATABASE_NAME =  "AmmarVisa"
DATA_INGESTION_DIR_NAME = "data_ingestion"
DATA_INGESTION_FEATURE_STORE_DIR = "feature_store"
DATA_INGESTION_INGESTED_DIR = "ingested"
DATA_INGESTION_TRAIN_TEST_SPLIT_RATIO = 0.20