import os


## DEFINING SOME COMMON CONSTANTS FOR TRAINING PIPELINE
TARGET_COLUMN = "case_status"
PIPELINE_NAME = "USVisa"
ARTIFACT_DIR = "artifacts"
FILE_NAME = "Visadataset.csv"
TRAIN_FILE_NAME = "train.csv"
TEST_FILE_NAME = "test.csv"
SCHEMA_FILE_PATH = os.path.join("data_schema", "schema.yaml")


## DATA INGESTION RELATED CONSTANTS STARTS WITH DATA_INGESTION VAR NAME 
DATA_INGESTION_COLLECTION_NAME = "VisaData"
DATA_INGESTION_DATABASE_NAME =  "AmmarVisa"
DATA_INGESTION_DIR_NAME = "data_ingestion"
DATA_INGESTION_FEATURE_STORE_DIR = "feature_store"
DATA_INGESTION_INGESTED_DIR = "ingested"
DATA_INGESTION_TRAIN_TEST_SPLIT_RATIO = 0.20


## DATA VALIDATION RELATED CONSTANTS STARTS WITH DATA_VALIDATION VAR NAME
DATA_VALIDATION_DIR_NAME = "data_validation"
DATA_VALIDATION_VALID_DIR = "valid"
DATA_VALIDATION_INVALID_DIR = "invalid"
DATA_VALIDATION_DRIFT_REPORT_DIR = "drift_report"
DATA_VALIDATION_DRIFT_REPORT_FILE_NAME = "report.yaml"  
